/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-04-07 07:33:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html >\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta content=\"UTF-8\">\r\n");
      out.write("<title>join</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../shadow/css/shadowbox.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"../shadow/js/shadowbox.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".row{ \r\n");
      out.write("\tmargin: 0px auto;\r\n");
      out.write("\twidth: 1000px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("input, select {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write(".table, td {\r\n");
      out.write("\t background-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("/* 창을 html형식으로 띄운다 */\r\n");
      out.write("Shadowbox.init({\r\n");
      out.write(" \tplayers:['iframe']\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("// jquery  ; window.onload ~ main()\r\n");
      out.write("// $(document).ready(function()){})   ==> 앞을 생략해서 아래의 결과가 나온다 (처리함수)\r\n");
      out.write("// var id=document.getElementById('id') : js <=====<input type=text id=id size=10>====> lib : $('#id')\r\n");
      out.write("/* \r\n");
      out.write("\t\tJavaScript / Jquery  == 태그를 제어하는 DOM 프로그램\r\n");
      out.write("\t\tselector\r\n");
      out.write("\t\t====\t\t\t\r\n");
      out.write("\t\t\t1) 태그 => $('태그명') \r\n");
      out.write("\t\t\t2) ID   => $('#id')\r\n");
      out.write("\t\t\t3) CLASS => $('.클래스명')\r\n");
      out.write("\t\t\t4) 가상  => 자신, 내장객체 => $(this), $(window), $(document)\r\n");
      out.write("\r\n");
      out.write("*/\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\t\t\t\t// onClick=\"함수명\"\r\n");
      out.write("\t\t\t\t/*\r\n");
      out.write("\t\t\t\t\t태그로 제어 : CSS제어, 이벤트 발생\r\n");
      out.write("\t\t\t\t*/\r\n");
      out.write("\t$('#postBtn').click(function(){\r\n");
      out.write("\t\t\t// 다음의 창을 띄워라\r\n");
      out.write("\t\t\tShadowbox.open({\r\n");
      out.write("\t\t\t\t content:'../member/postfind.do',     // 별도의 창이니까 postfind.jsp에서 처리함 (join아님)\r\n");
      out.write("\t\t\t\t title:'우편번호검색',\r\n");
      out.write("\t\t\t\t // html - iframe (include의미)\r\n");
      out.write("\t\t\t\t player:'iframe',\r\n");
      out.write("\t\t\t\t width:530,\r\n");
      out.write("\t\t\t\t height:400\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(" .row {\r\n");
      out.write(" \tmargin: 0px auto;\r\n");
      out.write(" \twidth: 700px;\r\n");
      out.write(" }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<h1 class=\"text-center\">회원가입</h1>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t<form name=\"frm\" action=\"join_ok.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t<table class=\"table table-hover\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th width=15% class=\"danger text-right\" >ID</th>\r\n");
      out.write("\t\t\t\t\t<td width=85%>\r\n");
      out.write("\t\t\t\t\t\t<input type=text name=id size=15 class=\"input-sm\" readonly>\r\n");
      out.write("\t\t\t\t\t\t<input type=button value=\"중복체크\" class=\"btn btn-sm btn-danger\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th width=15% class=\"danger text-right\" >비밀번호</th>\r\n");
      out.write("\t\t\t\t\t<td width=85%>\r\n");
      out.write("\t\t\t\t\t\t<input type=password name=pwd size=15 class=\"input-sm\">&nbsp;\r\n");
      out.write("\t\t\t\t\t\t재입력:<input type=password name=pwd1 size=15 class=\"input-sm\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th width=15% class=\"danger text-right\" >이름</th>\r\n");
      out.write("\t\t\t\t\t<td width=85%>\r\n");
      out.write("\t\t\t\t\t\t<input type=text name=name size=15 class=\"input-sm\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th width=15% class=\"danger text-right\" >이메일</th>\r\n");
      out.write("\t\t\t\t\t<td width=85%>\r\n");
      out.write("\t\t\t\t\t\t<input type=text name=e-mail size=50 class=\"input-sm\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th width=15% class=\"danger text-right\" >성별</th>\r\n");
      out.write("\t\t\t\t\t<td width=85%>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=sex value=\"남자\" checked=\"checked\">남자\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=sex value=\"여자\">여자\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th width=15% class=\"danger text-right\" >생일</th>\r\n");
      out.write("\t\t\t\t\t<td width=85%>\r\n");
      out.write("\t\t\t\t\t\t<input type=date name=birthday size=15 class=\"input-sm\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th width=15% class=\"danger text-right\" >우편번호</th>\r\n");
      out.write("\t\t\t\t\t<td width=85%>\r\n");
      out.write("\t\t\t\t\t\t<input type=text name=post1 size=5 class=\"input-sm\" readonly>   - \r\n");
      out.write("\t\t\t\t\t\t<input type=text name=post2 size=5 class=\"input-sm\" readonly>\r\n");
      out.write("\t\t\t\t\t\t<input type=button class=\"btn btn-sm btn-primary\" value=\"우편번호검색\" id=\"postBtn\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th width=15% class=\"danger text-right\" >주소</th>\r\n");
      out.write("\t\t\t\t\t<td width=85%>\r\n");
      out.write("\t\t\t\t\t\t<input type=text name=addr size=50 class=\"input-sm\" readonly>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th width=15% class=\"danger text-right\" >상세주소</th>\r\n");
      out.write("\t\t\t\t\t<td width=85%>\r\n");
      out.write("\t\t\t\t\t\t<input type=text name=addr2 size=50 class=\"input-sm\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th width=15% class=\"danger text-right\" >전화번호</th>\r\n");
      out.write("\t\t\t\t\t<td width=85%>\r\n");
      out.write("\t\t\t\t\t\t<select class=\"input-sm\" name=\"tel1\">\r\n");
      out.write("\t\t\t\t\t\t\t<option>010</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>011</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>017</option>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t<input type=text name=tel2 size=5 class=\"input-sm\">  -\r\n");
      out.write("\t\t\t\t\t\t<input type=text name=tel3 size=7 class=\"input-sm\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th width=15% class=\"danger text-right\" >소개</th>\r\n");
      out.write("\t\t\t\t\t<td width=85%>\r\n");
      out.write("\t\t\t\t\t\t<textarea rows=\"8\" cols=\"60\" name=\"content\"></textarea>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=2 class=\"text-center\">\r\n");
      out.write("\t\t\t\t\t\t<input type=button value=\"회원가입\" class=\"btn btn-sm btn-info\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"join()\"\r\n");
      out.write("\t\t\t\t\t\t>\r\n");
      out.write("\t\t\t\t\t\t<input type=button value=\"취소\" class=\"btn btn-sm btn-success\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"javascript:history.back()\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
