/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-04-01 08:54:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.reservation;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class reservation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<title>서:행 #예약하기</title>\n");
      out.write("\n");
      out.write("<!-- Bootstrap -->\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"../css/bootstrap.min.css\" />\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"../css/body.css\" />\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\">\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?\n");
      out.write("\n");
      out.write("appkey=daa1bab66cbb2b154fbe99cf1dfdb247\"></script>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\n");
      out.write("href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Montserrat\"\n");
      out.write("\n");
      out.write("rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<!-- Google font -->\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?\n");
      out.write("family=Montserrat:400,700,900\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!--\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/linearicons.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/font-awesome.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/bootstrap.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/magnific-popup.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/nice-select.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/animate.min.css\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/owl.carousel.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/main.css\"> -->\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body >\n");
      out.write("\n");
      out.write("<header id=\"header\">\n");
      out.write("\n");
      out.write("<div class=\"container box_1170 main-menu\">\n");
      out.write("\n");
      out.write("<div class=\"row align-items-center justify-content-\n");
      out.write("between d-flex\">\n");
      out.write("\n");
      out.write("<div id=\"logo\">\n");
      out.write("\n");
      out.write("<a href=\"#\"><img\n");
      out.write("\n");
      out.write("src=\"../img/logo.png\" alt=\"\" title=\"\" /></a>\n");
      out.write("</div>\n");
      out.write("<nav id=\"nav-menu-container\">\n");
      out.write("<ul class=\"nav-menu\">\n");
      out.write("\n");
      out.write("<li class=\"menu-active\"><a\n");
      out.write("\n");
      out.write("href=\"#\">Home</a></li>\n");
      out.write("\n");
      out.write("<li><a\n");
      out.write("\n");
      out.write("href=\"#\">Category</a></li>\n");
      out.write("\n");
      out.write("<li><a href=\"#\">Archive</a>\n");
      out.write("\n");
      out.write("</li>\n");
      out.write("\n");
      out.write("<li class=\"#\"><a\n");
      out.write("\n");
      out.write("href=\"\">Pages</a>\n");
      out.write("\n");
      out.write("</li>\n");
      out.write("\n");
      out.write("<li class=\"menu-has-\n");
      out.write("children\"><a href=\"\">Blog</a>\n");
      out.write("\n");
      out.write("</li>\n");
      out.write("<li><a href=\"#\">Contact</a>\n");
      out.write("\n");
      out.write("</li>\n");
      out.write("\n");
      out.write("</ul>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<div id=\"booking\" class=\"section\">\n");
      out.write("\n");
      out.write("<div class=\"section-center\">\n");
      out.write("<div class=\"container\">\n");
      out.write("<div class=\"row\">\n");
      out.write("\n");
      out.write("<div class=\"col-md-5\">\n");
      out.write("\n");
      out.write("<div class=\"booking-cta\">\n");
      out.write("\n");
      out.write("<!--vo.getName() -->\n");
      out.write("<h1>WXYZ Bar @\n");
      out.write("\n");
      out.write("Aloft Seoul Myeongdong</h1>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("<section>\n");
      out.write("\n");
      out.write("<div class=\"col-md-6 col-md-offset-\n");
      out.write("1\">\n");
      out.write("\n");
      out.write("<div class=\"booking-form\">\n");
      out.write("\n");
      out.write("<form>\n");
      out.write("<div\n");
      out.write("\n");
      out.write("class=\"row\">\n");
      out.write("<div class=\"col-md-6\">\n");
      out.write("\n");
      out.write("<div class=\"form-group\">\n");
      out.write("\n");
      out.write("<input class=\"form-control\" type=\"text\">\n");
      out.write("<span class=\"form-label\">Name</span>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("<div class=\"col-md-6\">\n");
      out.write("\n");
      out.write("<div class=\"form-group\">\n");
      out.write("\n");
      out.write("<input class=\"form-control\" type=\"email\">\n");
      out.write("<span class=\"form-label\">Email</span>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("<div\n");
      out.write("\n");
      out.write("class=\"row\">\n");
      out.write("<div class=\"col-md-6\">\n");
      out.write("\n");
      out.write("<div class=\"form-group\">\n");
      out.write("\n");
      out.write("<input class=\"form-control\" type=\"tel\">\n");
      out.write("<span class=\"form-label\">Phone</span>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("<div class=\"col-md-3 col-sm-6\">\n");
      out.write("<div class=\"form-group\">\n");
      out.write("\n");
      out.write("<span class=\"form-label\">Guests</span>\n");
      out.write("<select class=\"form-control\">\n");
      out.write("<option>1 Person</option>\n");
      out.write("<option>2 People</option>\n");
      out.write("<option>3 People</option>\n");
      out.write("<option>4 People</option>\n");
      out.write("\n");
      out.write("</select>\n");
      out.write("<span class=\"select-arrow\"></span>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("<div\n");
      out.write("\n");
      out.write("class=\"row\">\n");
      out.write("<div class=\"col-md-6\">\n");
      out.write("\n");
      out.write("<div class=\"form-group\">\n");
      out.write("\n");
      out.write("<input class=\"form-control\" type=\"date\" required>\n");
      out.write("<span class=\"form-label\">Date</span>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"col-md-6\">\n");
      out.write("\n");
      out.write("<div class=\"form-group\">\n");
      out.write("\n");
      out.write("<span class=\"form-label\">Time</span>\n");
      out.write("<select class=\"form-control\">\n");
      out.write("\n");
 // 시간 출력

int i=0;
for(i=13; i<18 ;i++)
{


      out.write("\n");
      out.write("\n");
      out.write("<option>");
      out.print(i

);
      out.write(":00</option>\n");
      out.write("\n");


}


      out.write("\n");
      out.write("\n");
      out.write("</select>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("<div\n");
      out.write("\n");
      out.write("class=\"form-btn\">\n");
      out.write("<button class=\"submit-btn\">Book Now</button>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<div id=\"myCarousel\" class=\"carousel slide text-center\" data-ride=\"carousel\">\n");
      out.write("<ol class=\"carousel-indicators\">\n");
      out.write("<li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\n");
      out.write("<li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\n");
      out.write("<li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\n");
      out.write("</ol>\n");
      out.write("\n");
      out.write("<div class=\"carousel-inner\" role=\"listbox\">\n");
      out.write("<div class=\"item active\">\n");
      out.write("\n");
      out.write("<img src=\"https://media-cdn.tripadvisor.com/media/photo-\n");
      out.write("o/11/49/bb/63/wxyz-bar.jpg\" alt=\"\">\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("<div class=\"item\">\n");
      out.write("\n");
      out.write("<img src=\"https://media-cdn.tripadvisor.com/media/photo-\n");
      out.write("f/11/49/bb/64/wxyz-hall.jpg\" alt=\"\">\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div id=\"map\" style=\"width:500px;height:300px; float:left;\">\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<a class=\"left carousel-control\" href=\"#myCarousel\" role=\"button\" data-\n");
      out.write("slide=\"prev\">\n");
      out.write("\n");
      out.write("<span class=\"glyphicon glyphicon-chevron-left\" aria-hidden=\"true\"></span>\n");
      out.write("<span class=\"sr-only\">Previous</span>\n");
      out.write("</a>\n");
      out.write("\n");
      out.write("<a class=\"right carousel-control\" href=\"#myCarousel\" role=\"button\" data-\n");
      out.write("slide=\"next\">\n");
      out.write("\n");
      out.write("<span class=\"glyphicon glyphicon-chevron-right\" aria-hidden=\"true\"></span>\n");
      out.write("<span class=\"sr-only\">Next</span>\n");
      out.write("</a>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("var container = document.getElementById('map');\n");
      out.write("var options = {\n");
      out.write("\n");
      out.write("center: new kakao.maps.LatLng(33.450701,\n");
      out.write("\n");
      out.write("126.570667),\n");
      out.write("\n");
      out.write("level: 3\n");
      out.write("\n");
      out.write("};\n");
      out.write("var map = new kakao.maps.Map(container, options);\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("<script src=\"js/jquery.min.js\"></script>\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("$('.form-control').each(function () {\n");
      out.write("floatedLabel($(this));\n");
      out.write("\n");
      out.write("});\n");
      out.write("$('.form-control').on('input', function () {\n");
      out.write("\n");
      out.write("floatedLabel($(this));\n");
      out.write("\n");
      out.write("});\n");
      out.write("function floatedLabel(input) {\n");
      out.write("\n");
      out.write("var $field = input.closest('.form-group');\n");
      out.write("if (input.val()) {\n");
      out.write("\n");
      out.write("$field.addClass('input-not-empty');\n");
      out.write("\n");
      out.write("} else {\n");
      out.write("\n");
      out.write("$field.removeClass('input-not-empty');\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</body><!-- This templates was made by Colorlib (https://colorlib.com) -->\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
