/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-04-07 00:01:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/webDev/webStudy/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/MVCLastProject/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1584582386016L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- ============================================ Image Slide ============================================ -->\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("  <div id=\"slider\" class=\"clear\"> \r\n");
      out.write("    <div class=\"flexslider basicslider\">\r\n");
      out.write("      <ul class=\"slides\">\r\n");
      out.write("        <li><img src=\"images/demo/slides/b1.jpg\" alt=\"\" width=100%>\r\n");
      out.write("          <div class=\"txtoverlay\">\r\n");
      out.write("            <div class=\"centralise\">\r\n");
      out.write("              <div class=\"verticalwrap\">\r\n");
      out.write("                <article>\r\n");
      out.write("                  <h2 class=\"heading uppercase\">여의도 월드나이트마켓</h2>\r\n");
      out.write("                  <p><a class=\"btn orange pushright\" href=\"#\">자세히 보기</a></p>\r\n");
      out.write("                </article>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div> \r\n");
      out.write("<!-- ============================================ 3개 메뉴 ============================================ -->\r\n");
      out.write("<div class=\"wrapper row2\">\r\n");
      out.write("  <div id=\"services\" class=\"clear\"> \r\n");
      out.write("    <div class=\"group\">\r\n");
      out.write("      <div class=\"one_third first\">\r\n");
      out.write("        <article class=\"service\"><i class=\"icon red circle fa fa-bell-o\"></i>\r\n");
      out.write("          <h2 class=\"heading\" style=\"font-family: 맑은 고딕\">한류관광</h2>\r\n");
      out.write("          <p class=\"btmspace-10\">서울의 10대 한류명소<br>\r\n");
      out.write("                  한류스타 출연 공연 일정<br>\r\n");
      out.write("          K-pop & K-drama 추천코스\r\n");
      out.write("          </p>\r\n");
      out.write("          <p><a href=\"#\">Read More &raquo;</a></p>\r\n");
      out.write("        </article>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"one_third\">\r\n");
      out.write("        <article class=\"service\"><i class=\"icon orange circle fa fa-bicycle\"></i>\r\n");
      out.write("          <h2 class=\"heading\" style=\"font-family: 맑은 고딕\">추천코스</h2>\r\n");
      out.write("          <p class=\"btmspace-10\">서울 한 바퀴<br>\r\n");
      out.write("          2019 창경궁 야간 상시관람<br>\r\n");
      out.write("                   서울의 무인서비스\r\n");
      out.write("          </p>\r\n");
      out.write("          <p><a href=\"#\">Read More &raquo;</a></p>\r\n");
      out.write("        </article>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"one_third\">\r\n");
      out.write("        <article class=\"service\"><i class=\"icon green circle fa fa-mortar-board\"></i>\r\n");
      out.write("          <h2 class=\"heading\" style=\"font-family: 맑은 고딕\">공연예약</h2>\r\n");
      out.write("          <p class=\"btmspace-10\">\r\n");
      out.write("                   아라리오뮤지엄 인 스페이스 서울<br>\r\n");
      out.write("                   모던 앤 클래식 3<br>\r\n");
      out.write("                   난타(NANTA) - 명동공연\r\n");
      out.write("          </p>\r\n");
      out.write("          <p><a href=\"#\">Read More &raquo;</a></p>\r\n");
      out.write("        </article>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"clear\"></div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ============================================ 레시피 (초록색) ============================================ -->\r\n");
      out.write("<div class=\"wrapper row6\">\r\n");
      out.write("  <section id=\"cta\" class=\"clear\"> \r\n");
      out.write("    <div class=\"three_quarter first\">\r\n");
      out.write("      <h2 class=\"heading\" style=\"font-family: 맑은 고딕\">SIST Recipe</h2>\r\n");
      out.write("      <p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("개의 맛있는 레시피가 있습니다.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"one_quarter\"><a class=\"btn\" href=\"#\">Get it now <span class=\"fa fa-arrow-right\"></span></a></div>\r\n");
      out.write("  </section>\t\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ============================================ 5개짜리 맛집 이미지 ============================================ -->\r\n");
      out.write("<div class=\"wrapper row2\">\r\n");
      out.write("  <div class=\"latest\"> \r\n");
      out.write("    <ul class=\"nospace group\">\r\n");
      out.write("      ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ============================================ 랜덤 맛집 ============================================ -->\r\n");
      out.write(" <div class=\"wrapper row3\">\r\n");
      out.write("  <main class=\"container nospace clear\"> \r\n");
      out.write("    <div class=\"group\">\r\n");
      out.write("      <div class=\"one_half first paditout\">\r\n");
      out.write("        <h2 class=\"heading uppercase btmspace-50\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fvo.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2>\r\n");
      out.write("        <ul class=\"nospace group\">\r\n");
      out.write("          <li class=\"btmspace-30\">\r\n");
      out.write("            <article class=\"service largeicon\"><i class=\"icon nobg circle fa fa-ra\"></i>\r\n");
      out.write("              <h6 class=\"heading\"><a href=\"#\">주소</a></h6>\r\n");
      out.write("              <p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fvo.address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fvo.tel}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("            </article>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"btmspace-30\">\r\n");
      out.write("            <article class=\"service largeicon\"><i class=\"icon nobg circle fa fa-female\"></i>\r\n");
      out.write("              <h6 class=\"heading\"><a href=\"#\">음식종류</a></h6>\r\n");
      out.write("              <p>\r\n");
      out.write("                \t\t\t ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fvo.type}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("              </p>\r\n");
      out.write("            </article>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <article class=\"service largeicon\"><i class=\"icon nobg circle fa fa-history\"></i>\r\n");
      out.write("              <h6 class=\"heading\"><a href=\"#\">가격대</a></h6>\r\n");
      out.write("              <p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fvo.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("            </article>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"one_half\"><a href=\"#\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fvo.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"\"></a></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"clear\"></div>\r\n");
      out.write("  </main>\r\n");
      out.write("</div> \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /main/home.jsp(29,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("vo");
      // /main/home.jsp(29,8) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${clist}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t        <li><img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.poster}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"\">\r\n");
            out.write("\t\t\t\t          <div class=\"txtoverlay\">\r\n");
            out.write("\t\t\t\t            <div class=\"centralise\">+\r\n");
            out.write("\t\t\t\t              <div class=\"verticalwrap\">\r\n");
            out.write("\t\t\t\t                <article>\r\n");
            out.write("\t\t\t\t                  <h2 class=\"heading uppercase\">\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"</h2>\r\n");
            out.write("\t\t\t\t                  <p><a class=\"btn red\" href=\"#\">자세히 보기</a></p>Z\r\n");
            out.write("\t\t\t\t                </article>\r\n");
            out.write("\t\t\t\t              </div>\r\n");
            out.write("\t\t\t\t            </div>\r\n");
            out.write("\t\t\t\t          </div>\r\n");
            out.write("\t\t\t\t        </li>\r\n");
            out.write("        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /main/home.jsp(100,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("vo");
      // /main/home.jsp(100,6) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rlist}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t      <li>\r\n");
            out.write("\t\t\t\t        <figure><a class=\"overlay\" href=\"#\"><img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.poster}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"\"/></a>\r\n");
            out.write("\t\t\t\t          <figcaption class=\"inspace-30 center\">\r\n");
            out.write("\t\t\t\t            <p class=\"bold uppercase\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("\t\t\t\t            <p style=\"color:#FC6\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.chef}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("\t\t\t\t            <p><a href=\"#\">View Here &raquo;</a></p>\r\n");
            out.write("\t\t\t\t          </figcaption>\r\n");
            out.write("\t\t\t\t        </figure>\r\n");
            out.write("\t\t\t\t      </li>\r\n");
            out.write("      ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
