/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-04-07 00:29:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/webDev/webStudy/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/MVCLastProject/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1584582386016L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>SIST Seoul Travel</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">\r\n");
      out.write("<link href=\"../main/layout/styles/layout.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\">\t\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body{\r\n");
      out.write("  font-family: 맑은 고딕;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"top\">\r\n");
      out.write("<!-- ============================================ Header ============================================ -->\r\n");
      out.write("<div class=\"wrapper row1\">\r\n");
      out.write("  <header id=\"header\" class=\"clear\"> \r\n");
      out.write("    <div id=\"logo\" class=\"fl_left\">\r\n");
      out.write("      <h1><a href=\"index.html\">SIST Recipe&Food</a></h1>\r\n");
      out.write("    </div>\r\n");
      out.write("    <nav id=\"mainav\" class=\"fl_right\">\r\n");
      out.write("      <ul class=\"clear\">\r\n");
      out.write("        <li class=\"active\"><a href=\"../main/main.do\">Home</a></li>\r\n");
      out.write("        <li><a class=\"drop\" href=\"#\">회원</a>\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li><a href=\"../member/join.do\">회원가입</a></li>\r\n");
      out.write("            <li><a href=\"pages/full-width.html\">아이디찾기</a></li>\r\n");
      out.write("            <li><a href=\"pages/sidebar-left.html\">비밀번호찾기</a></li>\r\n");
      out.write("            <li><a href=\"pages/sidebar-right.html\">회원탈퇴</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li><a class=\"drop\" href=\"#\">레시피</a>\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li><a href=\"../recipe/recipe.do\">레시피</a></li>\r\n");
      out.write("            <li><a class=\"drop\" href=\"#\">셰프</a>\r\n");
      out.write("              <ul>\r\n");
      out.write("                <li><a href=\"../recipe/chef.do\">쉐프목록</a></li>\r\n");
      out.write("                <li><a href=\"#\">레시피찾기</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li><a class=\"drop\" href=\"#\">맛집</a>\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li><a href=\"#\">추천코스</a></li>\r\n");
      out.write("            <li><a href=\"#\">명소</a></li>\r\n");
      out.write("            <li><a href=\"#\">쇼핑</a></li>\r\n");
      out.write("            <li><a href=\"#\">숙박</a></li>\r\n");
      out.write("            <li><a href=\"#\">음식점</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li><a class=\"drop\" href=\"#\">예약하기</a>\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li><a href=\"#\">맛집예약</a></li>\r\n");
      out.write("            <li><a href=\"#\">호텔예약</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li><a class=\"drop\" href=\"#\">커뮤니티</a>\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li><a href=\"#\">자유게시판</a></li>\r\n");
      out.write("            <li><a href=\"#\">묻고답하기</a></li>\r\n");
      out.write("            <li><a href=\"#\">자료실</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li><a href=\"#\">공지사항</a></li>\r\n");
      out.write("        <li><a href=\"#\">마이페이지</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("   </header>\r\n");
      out.write("  </div>\r\n");
      out.write("<!-- ============================================ 로그인 ============================================ -->\r\n");
      out.write(" \t\t<div class=\"row1\">\r\n");
      out.write(" \t\t   <div class=\"clear\" style=\"margin-left: 1400px\">\r\n");
      out.write("  \t\t \t\t<input type=text size=10 class=\"input-sm\" placeholder=\"ID\" style=\"display:inline-block;\">\r\n");
      out.write("  \t\t \t\t&nbsp;\r\n");
      out.write("  \t\t \t\t<input type=password size=10 class=\"input-sm\" placeholder=\"Password\" style=\"display:inline-block;\">\r\n");
      out.write("  \t\t \t\t<input type=button class=\"btn btn-sm primary\" value=\"로그인\">\r\n");
      out.write("  \t\t \t</div>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("\t\t<div style=\"height: 30px\"></div>\r\n");
      out.write("\r\n");
      out.write("<!-- ################################################################################################ -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${main_jsp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), out, false);
      out.write("\r\n");
      out.write("<!--=====================================================================================================  -->\r\n");
      out.write(" \r\n");
      out.write("  <footer id=\"footer\" class=\"clear\"> \r\n");
      out.write("    <!-- ################################################################################################ -->\r\n");
      out.write("    <div class=\"one_quarter first\">\r\n");
      out.write("      <h6 class=\"title\">공지사항</h6>\r\n");
      out.write("      <ul class=\"nospace linklist\">\r\n");
      out.write("        <li><a href=\"#\">좌석을 변경할 수 있나요?</a></li>\r\n");
      out.write("        <li><a href=\"#\">예약은 어떻게 취소하나요?</a></li>\r\n");
      out.write("        <li><a href=\"#\">예약을 일부만 취소할 수 있나요? </a></li>\r\n");
      out.write("        <li><a href=\"#\">티켓은 어디서 받나요?</a></li>\r\n");
      out.write("        <li><a href=\"#\">관광시간이 긴데 줄일 수 없나요?</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"one_quarter\">\r\n");
      out.write("      <h6 class=\"title\">인기게시물</h6>\r\n");
      out.write("      <ul class=\"nospace linklist\">\r\n");
      out.write("        <li><a href=\"#\">좌석을 변경할 수 있나요?</a></li>\r\n");
      out.write("        <li><a href=\"#\">예약은 어떻게 취소하나요?</a></li>\r\n");
      out.write("        <li><a href=\"#\">예약을 일부만 취소할 수 있나요? </a></li>\r\n");
      out.write("        <li><a href=\"#\">티켓은 어디서 받나요?</a></li>\r\n");
      out.write("        <li><a href=\"#\">관광시간이 긴데 줄일 수 없나요?</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"one_quarter\">\r\n");
      out.write("      <h6 class=\"title\">이벤트</h6>\r\n");
      out.write("      <ul class=\"nospace linklist\">\r\n");
      out.write("        <li><a href=\"#\">좌석을 변경할 수 있나요?</a></li>\r\n");
      out.write("        <li><a href=\"#\">예약은 어떻게 취소하나요?</a></li>\r\n");
      out.write("        <li><a href=\"#\">예약을 일부만 취소할 수 있나요? </a></li>\r\n");
      out.write("        <li><a href=\"#\">티켓은 어디서 받나요?</a></li>\r\n");
      out.write("        <li><a href=\"#\">관광시간이 긴데 줄일 수 없나요?</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"one_quarter\">\r\n");
      out.write("      <h6 class=\"title\">인기검색어</h6>\r\n");
      out.write("      <ul class=\"nospace linklist\">\r\n");
      out.write("      \r\n");
      out.write("        <li><a href=\"#\">좌석을 변경할 수 있나요?</a></li>\r\n");
      out.write("        <li><a href=\"#\">예약은 어떻게 취소하나요?</a></li>\r\n");
      out.write("        <li><a href=\"#\">예약을 일부만 취소할 수 있나요? </a></li>\r\n");
      out.write("        <li><a href=\"#\">티켓은 어디서 받나요?</a></li>\r\n");
      out.write("        <li><a href=\"#\">관광시간이 긴데 줄일 수 없나요?</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ################################################################################################ -->\r\n");
      out.write("  \t\r\n");
      out.write("  </footer>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ################################################################################################ -->\r\n");
      out.write("<!-- ################################################################################################ -->\r\n");
      out.write("<!-- ################################################################################################ -->\r\n");
      out.write("<div class=\"wrapper row5\">\r\n");
      out.write("  <div id=\"copyright\" class=\"clear\"> \r\n");
      out.write("    <!-- ################################################################################################ -->\r\n");
      out.write("    <p class=\"fl_left\"><a href=\"#\">SIST 쌍용 강북 교육센터</a></p>\r\n");
      out.write("    <p class=\"fl_right\"><a target=\"_blank\" href=\"#\" title=\"Free Website Templates\">G강의장</a></p>\r\n");
      out.write("    <!-- ################################################################################################ -->\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ################################################################################################ -->\r\n");
      out.write("<!-- ################################################################################################ -->\r\n");
      out.write("<!-- ################################################################################################ -->\r\n");
      out.write("<a id=\"backtotop\" href=\"#top\"><i class=\"fa fa-chevron-up\"></i></a> \r\n");
      out.write("<!-- JAVASCRIPTS -->\r\n");
      out.write("<script src=\"../main/layout/scripts/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"../main/layout/scripts/jquery.backtotop.js\"></script>\r\n");
      out.write("<script src=\"../main/layout/scripts/jquery.mobilemenu.js\"></script>\r\n");
      out.write("<script src=\"../main/layout/scripts/jquery.flexslider-min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
