/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-04-07 08:50:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jquery;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class jquery6_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<!-- 이미지를 클릭하면 상세보기가 다이얼로그로 뜨는 프로그래밍  -->\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/resources/demos/style.css\">\r\n");
      out.write("  <script src=\"https://code.jquery.com/jquery.js\"></script>\r\n");
      out.write("  <script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("  // JSON파일을 append 함수로 읽어오기\r\n");
      out.write("  $( function() {\r\n");
      out.write("   \t $.getJSON('weekly.json',function(data){\r\n");
      out.write("   \t\t //\talert(data)\r\n");
      out.write("   \t\t \t// for each 구문 ! [\"key\"]\r\n");
      out.write("   \t\t $.each(data[\"datas\"],function(key,value){\r\n");
      out.write("   \t\t\t $('#list').append(\r\n");
      out.write("   \t\t\t\t\t'<div class=\"col-md-3\">'\r\n");
      out.write("   \t\t\t\t    +'<div class=\"thumbnail\">'\r\n");
      out.write("   \t\t\t\t   \r\n");
      out.write("   \t\t\t\t        +'<img src=\"'+value.poster+'\" alt=\"Lights\" style=\"width:100%\" onclick=detail('+value.no+')>'\r\n");
      out.write("   \t\t\t\t        +'<div class=\"caption\">'\r\n");
      out.write("   \t\t\t\t         +'<p id=\"ppp\">'+value.title+'</p>'\r\n");
      out.write("   \t\t\t\t        +'</div>'\r\n");
      out.write("\r\n");
      out.write("   \t\t\t\t    +'</div>'\r\n");
      out.write("   \t\t\t\t +'</div>'\r\n");
      out.write("   \t\t\t )\r\n");
      out.write("   \t\t });\r\n");
      out.write("   \t });\r\n");
      out.write("   \t $('#ppp').click(function(){\r\n");
      out.write("   \t\t let p=$(this).text();\r\n");
      out.write("   \t\t alert(p);\r\n");
      out.write("   \t })\r\n");
      out.write("  });\r\n");
      out.write("  \r\n");
      out.write("   \t function detail(no)\r\n");
      out.write("   \t {\r\n");
      out.write("   \t\t$.getJSON('weekly.json',function(data){\r\n");
      out.write("      \t\t //\talert(data)\r\n");
      out.write("      \t\t \t// for each 구문 ! [\"key\"]\r\n");
      out.write("      \t\t $.each(data[\"datas\"],function(key,value){\r\n");
      out.write("      \t\t\t if(no==value.no)\r\n");
      out.write("      \t\t\t {\r\n");
      out.write("      \t\t\t\t $('#img').attr(\"src\",value.poster);\r\n");
      out.write("      \t\t\t\t $('#title').text(value.title);\r\n");
      out.write("      \t\t\t\t $('#director').text(value.director);\r\n");
      out.write("      \t\t\t\t $('#regdate').text(value.regdate);\r\n");
      out.write("      \t\t\t\t $('#grade').text(value.grade);\r\n");
      out.write("      \t\t\t\t $('#score').text(value.score);\r\n");
      out.write("      \t\t\t\t $('#actor').text(value.actor);\r\n");
      out.write("      \t\t\t\t $('#story').text(value.story);\r\n");
      out.write("      \t\t\t\r\n");
      out.write("      \t\t\t\t // 함수종료는 return으로 한다.\r\n");
      out.write("      \t\t\t\t return true;\r\n");
      out.write("      \t\t\t }\r\n");
      out.write("      \t\t\t\r\n");
      out.write("      \t\t });\r\n");
      out.write("      \t });\r\n");
      out.write("      \t \r\n");
      out.write("   \t\t// dialog 띄울 때 detail함수를 호출하라\r\n");
      out.write("      \t $('#dialog').dialog({\r\n");
      out.write("      \t\twidth:600,\r\n");
      out.write("      \t\theight:500\r\n");
      out.write("      \t })\r\n");
      out.write("   \t }\r\n");
      out.write("\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!--  \r\n");
      out.write("\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t    <div class=\"thumbnail\">\r\n");
      out.write("\t\t\t      <a href=\"/w3images/lights.jpg\">\r\n");
      out.write("\t\t\t        <img src=\"/w3images/lights.jpg\" alt=\"Lights\" style=\"width:100%\">\r\n");
      out.write("\t\t\t        <div class=\"caption\">\r\n");
      out.write("\t\t\t          <p>Lorem ipsum...</p>\r\n");
      out.write("\t\t\t        </div>\r\n");
      out.write("\t\t\t      </a>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("-->\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<h1 class=\"text-center\">영화목록</h1>\r\n");
      out.write("\t\t<div class=\"row\" id=\"list\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t<div id=\"dialog\" title=\"영화 상세보기\" style=\"display:none\">\r\n");
      out.write(" \t\t\t <table class=\"table\">\r\n");
      out.write(" \t\t\t \t<tr>\r\n");
      out.write(" \t\t\t \t\t<td width=30% class=\"text-center\" rowspan=\"7\">\r\n");
      out.write(" \t\t\t \t\t\t<img src=\"\" width=100% id=\"img\">\r\n");
      out.write(" \t\t\t \t\t</td>\r\n");
      out.write(" \t\t\t \t\t<td colspan=\"2\" id=\"title\"></td>\r\n");
      out.write(" \t\t\t \t</tr>\r\n");
      out.write(" \t\t\t \t<tr>\r\n");
      out.write(" \t\t\t \t\t<td width=10% class=\"text-right\"></td>\r\n");
      out.write(" \t\t\t \t\t<td width=60% id=\"director\">감독</td>\r\n");
      out.write(" \t\t\t \t</tr>\r\n");
      out.write(" \t\t\t \t<tr>\r\n");
      out.write(" \t\t\t \t\t<td width=10% class=\"text-right\"></td>\r\n");
      out.write(" \t\t\t \t\t<td width=60% id=\"actor\">출연</td>\r\n");
      out.write(" \t\t\t \t</tr>\r\n");
      out.write(" \t\t\t \t<tr>\r\n");
      out.write(" \t\t\t \t\t<td width=10% class=\"text-right\"></td>\r\n");
      out.write(" \t\t\t \t\t<td width=60% id=\"genre\">장르</td>\r\n");
      out.write(" \t\t\t \t</tr>\r\n");
      out.write(" \t\t\t \t<tr>\r\n");
      out.write(" \t\t\t \t\t<td width=10% class=\"text-right\"></td>\r\n");
      out.write(" \t\t\t \t\t<td width=60% id=\"grade\">등급</td>\r\n");
      out.write(" \t\t\t \t</tr>\r\n");
      out.write(" \t\t\t \t<tr>\r\n");
      out.write(" \t\t\t \t\t<td width=10% class=\"text-right\"></td>\r\n");
      out.write(" \t\t\t \t\t<td width=60% id=\"score\">평점</td>\r\n");
      out.write(" \t\t\t \t</tr>\r\n");
      out.write(" \t\t\t \t<tr>\r\n");
      out.write(" \t\t\t \t\t<td width=10% class=\"text-right\"></td>\r\n");
      out.write(" \t\t\t \t\t<td width=60% id=\"regdate\">상영일</td>\r\n");
      out.write(" \t\t\t \t</tr>\r\n");
      out.write(" \t\t\t \t<tr >\r\n");
      out.write(" \t\t\t \t\t<td colspan=\"3\" class=\"text-left\" id=\"story\"></td>\r\n");
      out.write(" \t\t\t \t</tr>\r\n");
      out.write(" \t\t\t \t\r\n");
      out.write(" \t\t\t </table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
