/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-03-11 07:17:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.sist.dao.*;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.sist.dao");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("   ");

   		String no=request.getParameter("no");
  
   		//Detail.jsp에서 값을 받아야 됨
   		String strPage=request.getParameter("page");
   		
   		// no=>DAO=> VO=> HTML
   		BoardDAO dao=new BoardDAO();
   		BoardVO vo=dao.boardDetailData(Integer.parseInt(no), 0); 
   		
   
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Detail</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/bootstrap.min.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".row {\r\n");
      out.write("\tmargin: 0px auto;\r\n");
      out.write("\twidth: 800px;\r\n");
      out.write("}\r\n");
      out.write("h2 {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- JQuery!  ; JavaScript Library = onload 상태에서 태그를 제어한다 -->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t/*\r\n");
      out.write("\t\t\t\t\t 자바스크립트 코딩\r\n");
      out.write("\t\t\t\t\t window.onload=function()\r\n");
      out.write("\t\t\t\t\t {}\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t 자바 코딩\r\n");
      out.write("\t\t\t\t\t function delClick() {}\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t 자바 스크립트 코딩\r\n");
      out.write("\t\t\t\t\t document.getElementById(\"delBtn\");\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t CSS\r\n");
      out.write("\t\t\t\t\t [Selector]\r\n");
      out.write("\t\t\t\t\t - tag  \ttd{}\r\n");
      out.write("\t\t\t\t\t - ID\t  \t#id{}\r\n");
      out.write("\t\t\t\t\t - Class\t.class{}\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t ; <a>bbb</a>  \t\t\t\t\t\t\t\t\t$('a').text() \t\t=>setter \t    :~bbb\r\n");
      out.write("\t\t\t\t\t ; <a></a>\t\t\t\t\t\t\t\t\t\t\t$('a').text(\"bbb\")  => getter\t\t: bbb입력\r\n");
      out.write("\t\t\t\t\t ; <a href=\"kkk\" id=\"k\"> \t\t\t\t\t\t$('#k').attr(\"href\")  \t\t\t\t\t: ~kkk\r\n");
      out.write("\t\t\t\t\t ; <input type=text id=\"p\" value=\"kkk\"> \t$('#p').val()\t\t\t\t\t\t\t:  kkk\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$('#p').val(\"ttt\")\t\t\t\t\t\t: ttt입력\t\r\n");
      out.write("\t\t\t\t\t; <td><span>ooo</span></td>\t\t\t$('td').text() \t\t\t\t\t\t\t: ooo\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$('td>span').text() \t\t\t\t\t: ooo\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$('td').html() \t\t\t\t\t\t\t: <span>ooo</span>\r\n");
      out.write("\t\t\t\t\t */\r\n");
      out.write(" // 전역변수\r\n");
      out.write(" var i=0;\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("//Jquery  = DOM (태그 제어 프로그램) \r\n");
      out.write("$(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t//보여주기\r\n");
      out.write("\t$('#delBtn').click(function(){\r\n");
      out.write("\t\tif(i==0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t$('#delBtn').val(\"취소\");\r\n");
      out.write("\t\t\t//비밀번호 창 보여주기\r\n");
      out.write("\t\t\t$('#del').show();\r\n");
      out.write("\t\t\t// 다음엔 else로 들어가게끔\r\n");
      out.write("\t\t\ti=1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t$('#delBtn').val(\"삭제\");\r\n");
      out.write("\t\t\t//비밀번호 창 감추기\r\n");
      out.write("\t\t\t$('#del').hide();\r\n");
      out.write("\t\t\t// 다음엔 if문으로 들어가게끔\r\n");
      out.write("\t\t\ti=0; \r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//실제 처리 --- Ajax ; id중복체크 / 화면 안 깜빡거리고 바로 값을 주고, 받고 할 수 있는 코딩 / 화면이 바뀌지 않아도 처리할 수 있음\r\n");
      out.write("\t$('#sendBtn').click(function(){\r\n");
      out.write("\t\tvar pwd=$('#pwd').val();\r\n");
      out.write("\t\tvar no=$('#no').val();\r\n");
      out.write("\t\tvar page=$('#page').val();\r\n");
      out.write("\t\tif(pwd==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t$('#pwd').focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//Ajax , JSON방식\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t//delete.jsp?no=1&pwd=1234  => 404(경로), 500(소스), 200(정상)\r\n");
      out.write("\t\t\ttype:'POST',\r\n");
      out.write("\t\t\turl:'delete.jsp',\r\n");
      out.write("\t\t\tdata:{\"no\":no,\"pwd\":pwd},\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//200이면\r\n");
      out.write("\t\t\tsuccess:function(res)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t//alert(res);\r\n");
      out.write("\t\t\t\t//delete.jsp에서 넘어오는 변수 : res (0|1)\r\n");
      out.write("\t\t\t\tvar result=res.trim();\r\n");
      out.write("\t\t\t\tif(result==0)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\talert(\"비밀번호가 틀립니다\");\r\n");
      out.write("\t\t\t\t\t$('#pwd').val(''); // 공백화\r\n");
      out.write("\t\t\t\t\t$('#pwd').focus();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t//★화면이동 =sendRedirect\r\n");
      out.write("\t\t\t\t\tlocation.href=\"list.jsp?page=\"+page;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t\t<h2>내용보기</h2>\r\n");
      out.write("\t\t\t<table class=\"table table-hover\" >\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th width=20% class=\"text-center success\">번호</th>\r\n");
      out.write("\t\t\t\t\t<td width=30% class=\"text-center \">");
      out.print( vo.getNo() );
      out.write(" </td>\t\t\r\n");
      out.write("\t\t\t\t\t<th width=20% class=\"text-center success\">작성일</th>\r\n");
      out.write("\t\t\t\t\t<td width=30% class=\"text-center \">");
      out.print( vo.getRegdate() );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th width=20% class=\"text-center success\">이름</th>\r\n");
      out.write("\t\t\t\t\t<td width=30% class=\"text-center \">");
      out.print( vo.getName() );
      out.write("</td>\t\t\r\n");
      out.write("\t\t\t\t\t<th width=20% class=\"text-center success\">조회수</th>\r\n");
      out.write("\t\t\t\t\t<td width=30% class=\"text-center \">");
      out.print( vo.getHit() );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t<th width=20% class=\"text-center success\">제목</th>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"3\" class=\"text-left \">");
      out.print(vo.getSubject() );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"4\" class=\"text-left\" valign=\"top\" height=\"200\">\r\n");
      out.write("\t\t\t\t\t\t<pre style=\"white-space: pre-wrap;  background-color: white; border:none \">");
      out.print( vo.getContent() );
      out.write("</pre>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"4\" class=\"text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"reply.jsp?no=");
      out.print(vo.getNo() );
      out.write("&page=");
      out.print(strPage );
      out.write("\" class=\"btn btn-xs btn-success\">답변</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"update.jsp?no=");
      out.print(vo.getNo() );
      out.write("&page=");
      out.print(strPage );
      out.write("\" class=\"btn btn-xs btn-primary\">수정</a>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=button class=\"btn btn-xs btn-danger\" id=\"delBtn\" value=\"삭제\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"list.jsp?page=");
      out.print(strPage );
      out.write("\" class=\"btn btn-xs btn-info\">목록</a> <!--  back을 하면 조회수에 문제가 생김 -->\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t<!-- 비밀번호 창 숨기기 -->\r\n");
      out.write("\t\t\t\t<tr id=\"del\" style=\"display:none\">\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"4\" class=\"text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t비밀번호:\t<input type=\"password\" id=\"pwd\" size=10 class=\"input-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=hidden id=\"no\" value=\"");
      out.print( no );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=hidden id=\"page\" value=\"");
      out.print( strPage);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"button\" value=\"삭제\" class=\"btn btn-sm btn-danger\" id=\"sendBtn\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
